name: Build Offline Go Tour

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install Go Tour
      run: |
        go install golang.org/x/website/tour@latest
        mkdir dist
        copy "%GOPATH%\bin\tour.exe" dist\

    - name: Create Zip Archive
      run: |
        cd dist
        7z a -r go-tour-${{ runner.os }}.zip *

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: go-tour-${{ runner.os }}
        path: |
          go-tour-${{ runner.os }}.zip
      
