name: Build Ollama (Windows Cross-Compile)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git golang-go mingw-w64

      - name: Set environment variables
        run: |
          echo "GOOS=windows" >> $GITHUB_ENV
          echo "GOARCH=amd64" >> $GITHUB_ENV
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "CC=x86_64-w64-mingw32-gcc" >> $GITHUB_ENV

      - name: Generate and build
        run: |
          go generate ./...
          go build -v -o ollama.exe .

      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ollama-windows
          path: ollama.exe
