name: Build Caddy

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Build platforms'
        required: true
        default: 'linux/arm64'
        type: choice
        options:
        - linux/arm64
        - linux/amd64
      # docker_tag:
      #   description: 'Docker base image tag'
      #   required: true
      #   default: '2.8.4'
      tag:
        description: 'My docker image tag'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
          
    # - name: Replace base image tag in Dockerfile
    #   run: |
    #     TAG=${{ github.event.inputs.tag }}
    #     sed -i "s|FROM caddy:builder-alpine AS builder|FROM caddy:${{ inputs.docker_tag }}-builder-alpine AS builder|" ./caddy/Dockerfile
    #     sed -i "s|FROM caddy:alpine|FROM caddy:${{ inputs.docker_tag }}-alpine|" ./caddy/Dockerfile

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./caddy
        platforms: ${{ inputs.platforms }}
        push: true
        tags: x1aobang/caddy:${{ inputs.tag }}
        file: ./caddy/Dockerfile