name: Build Vscode Online

on:
  workflow_dispatch:

jobs:
  build:
    name: Build Vscode Online
    runs-on: self-hosted
    container:
      image: ubuntu:22.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: vscode-online:latest
