name: Build My Dockerfile

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: input image name
        required: true
        type: text

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - working-directory: ./${{ inputs.image_name }}
        run: |
          docker build -t ${{ inputs.image_name }}:latest .
          docker save ${{ inputs.image_name }}:latest | gzip > ${{ inputs.image_name }}.tar.gz

      - name: 上传二进制产物
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.image_name }}
          path: ./${{ inputs.image_name }}/${{ inputs.image_name }}.tar.gz
