name: Download Image

on:
  workflow_dispatch:
    inputs:
      image_name:
        description: input image name
        required: true
        type: text

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: |
          echo "imagename=echo ${{ inputs.image_name }} | cut -d'/' -f2 | cut -d':' -f1" > $GITHUB_ENV

      - name: Pull Image
        run: docker pull ${{ inputs.image_name }}

      - name: Save Image
        run: docker save ${{ inputs.image_name }} | gzip > imagename.tar.gz

      - name: Upload Image
        uses: actions/upload-artifact@v4.6.2
        with:
          path: imagename.tar.gz
          
