name: Build Offline Go Tour

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install Go Tour
      run: |
        go install golang.org/x/website/tour@latest
        # 获取 tour.exe 的安装路径
        $tourPath = (Get-Command tour).Source
        # 创建打包目录
        New-Item -ItemType Directory -Path dist
        Copy-Item $tourPath -Destination dist\tour.exe

    - name: Create Zip Archive
      run: |
        Compress-Archive -Path dist/* -DestinationPath go-tour-windows.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: go-tour-${{ runner.os }}
        path: |
          go-tour-windows.zip
      
