name: Build Neovim Self

on:
  schedule:
    - cron: "0 4,16 * * *"
  workflow_dispatch:

# permissions:
#   contents: write
#   pages: write
#   id-token: write

jobs:
  build:
    name: Build Neovim with Docker
    runs-on: self-hosted
    container:
      image: bitnami/git:latest

    steps:
      - name: Check CPU and Memory Info
        run: |
          echo "CPU Info:"
          lscpu
          echo "Memory Info:"
          free -h
          echo "Disk Info:"
          df -h
  
      - name: 安装依赖
        run: |
          apt update
          apt install -y ninja-build gettext cmake unzip curl build-essential fakeroot dh-make

      - name: 获取仓库
        run: |
          git clone https://github.com/neovim/neovim.git
          cd neovim
          git checkout stable

      - name: 编译 Neovim
        shell: bash
        working-directory: ./neovim
        run: |
          make CMAKE_BUILD_TYPE=RelWithDebInfo

      - name: 打包 Neovim
        run: |
          cd neovim/build
          cpack -G DEB

      - name: 安装并验证
        run: |
          cd neovim/build
          dpkg -i nvim-linux-arm64.deb
          nvim --version

      # - name: 上传二进制产物
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: neovim-binary
      #     path: neovim/build/*.deb
