name: Build Caddy

on:
  workflow_dispatch:
    inputs:
      platforms:
        description: 'Build platforms'
        required: true
        default: 'linux/arm64'
        type: choice
        options:
        - linux/arm64
        - linux/amd64
      tag:
        description: 'Docker image tag'
        required: true
        default: 'latest'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        platforms: ${{ inputs.platforms }}
        push: true
        tags: x1aobang/caddy:${{ inputs.tag }}
        file: Dockerfile
