name: Build Ollama (Windows Cross-Compile)

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: self-hosted
    container:
      image: ubuntu:latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y build-essential git golang-go mingw-w64

      - name: Set environment variables
        run: |
          echo "GOOS=windows" >> $GITHUB_ENV
          echo "GOARCH=amd64" >> $GITHUB_ENV
          echo "CGO_ENABLED=1" >> $GITHUB_ENV
          echo "CC=x86_64-w64-mingw32-gcc" >> $GITHUB_ENV

      - name: Generate and build
        run: |
          git clone --depth=1 https://github.com/ollama/ollama.git
          cd ollama
          go generate ./...
          env GOOS=windows GOARCH=amd64 CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc go build -o ollama.exe .

      - name: Archive build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ollama-windows
          path: ollama.exe
