name: Build Ollama

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ollama/ollama
          ref: main

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.17'

      - name: Install dependencies
        run: go mod download

      - name: Install HIP SDK
        run: |
          Invoke-WebRequest -Uri "https://github.com/ROCm-Developer-Tools/HIP/archive/refs/heads/main.zip" -OutFile "hip-sdk.zip"
          Expand-Archive "hip-sdk.zip" -DestinationPath "hip-sdk"
          cd hip-sdk && .\install.ps1

      - name: Modify configuration files
        run: |
          $content = Get-Content -Path "llm/generate/gen_windows.ps1" -Raw
          $content = $content -replace 'gfx1102', 'gfx1103'
          Set-Content -Path "llm/generate/gen_windows.ps1" -Value $content

          $content = Get-Content -Path "ollama/gpu/amd_windows.go" -Raw
          $content = $content -replace 'iGPUName = "AMD Radeon\(TM\) Graphics"', 'iGPUName = "AMD 2024 Graphics"'
          Set-Content -Path "ollama/gpu/amd_windows.go" -Value $content

      - name: Build project
        run: |
          $env:CGO_ENABLED="1"
          go generate ./...
          go build .

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ollama
          path: |
            ollama.exe
