name: Build zh.javascript.info

on:
  workflow_dispatch:

# permissions:
#   contents: write
#   pages: write
#   id-token: write

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - working-directory: ./zh.javascript.info
        run: |
          docker build -t jsinfo:latest .
          docker save jsinfo:latest | gzip > jsinfo_latest.tar.gz

      - name: 上传二进制产物
        uses: actions/upload-artifact@v4
        with:
          name: jsinfo-docker
          path: ./zh.javascript.info/jsinfo_latest.tar.gz
